### ISSUE TITLE
[Vuetify] [BREAKING] 'box' has been removed, use 'filled' instead. For more information, see the upgrade guid

### ISSUE THREAD

**Issue by mean-cj** [Seokky/vuetify-number-smarty#1]
Hello

found the error on vuetifyjs 2.0.18

[Vuetify] [BREAKING] 'box' has been removed, use 'filled' instead. For more information, see the upgrade guid

https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0#user-content-upgrade-guide

Text Fields
Improve multiple style prop combination styles
Added new properties
filled - Replaces old box property

**Comment by Seokky** [comment]
Hi! Vuetify 2.0 is not stable yet.
